/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    reclaim: {
      address:
        "0x290a5f5a2c3326b905a9a74964814945eb0e3ed9b600403751201037871bd01",
      abi: [
        {
          type: "impl",
          name: "ReclaimImpl",
          interface_name: "contracts::reclaim::IReclaim",
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::reclaim::IReclaim",
          items: [
            {
              type: "function",
              name: "save_metadata",
              inputs: [
                {
                  name: "hash_commit",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "cipher_secret",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "cid",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "unlock_timestamp",
                  type: "core::felt252",
                },
                {
                  name: "access_type",
                  type: "core::felt252",
                },
                {
                  name: "name",
                  type: "core::byte_array::ByteArray",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "reclaim",
              inputs: [
                {
                  name: "hash_commit",
                  type: "core::byte_array::ByteArray",
                },
              ],
              outputs: [
                {
                  type: "(core::byte_array::ByteArray, core::byte_array::ByteArray, core::felt252, core::felt252, core::felt252, core::byte_array::ByteArray)",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_records_by_owner",
              inputs: [
                {
                  name: "owner",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::array::Array::<(core::byte_array::ByteArray, core::felt252, core::felt252, core::felt252, core::byte_array::ByteArray)>",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::reclaim::reclaim::MetadataSaved",
          kind: "struct",
          members: [
            {
              name: "hash_commit",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "unlock_timestamp",
              type: "core::felt252",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::reclaim::reclaim::FileReclaimed",
          kind: "struct",
          members: [
            {
              name: "hash_commit",
              type: "core::felt252",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::reclaim::reclaim::Event",
          kind: "enum",
          variants: [
            {
              name: "MetadataSaved",
              type: "contracts::reclaim::reclaim::MetadataSaved",
              kind: "nested",
            },
            {
              name: "FileReclaimed",
              type: "contracts::reclaim::reclaim::FileReclaimed",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x546340d4240be3f4ac7161a74ff23954192f0a77d69bc0e4e3fdcaae6b99e97",
    },
  },
  mainnet: {
    reclaim: {
      address:
        "0x60c32c24421a1067e1756766c49047dfc6b6d330e588b5c20a26fbb2ac74214",
      abi: [
        {
          type: "impl",
          name: "ReclaimImpl",
          interface_name: "contracts::reclaim::IReclaim",
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::reclaim::IReclaim",
          items: [
            {
              type: "function",
              name: "save_metadata",
              inputs: [
                {
                  name: "hash_commit",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "cipher_secret",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "cid",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "unlock_timestamp",
                  type: "core::felt252",
                },
                {
                  name: "access_type",
                  type: "core::felt252",
                },
                {
                  name: "name",
                  type: "core::byte_array::ByteArray",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "reclaim",
              inputs: [
                {
                  name: "hash_commit",
                  type: "core::byte_array::ByteArray",
                },
              ],
              outputs: [
                {
                  type: "(core::byte_array::ByteArray, core::byte_array::ByteArray, core::felt252, core::felt252, core::felt252, core::byte_array::ByteArray)",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_records_by_owner",
              inputs: [
                {
                  name: "owner",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::array::Array::<(core::byte_array::ByteArray, core::felt252, core::felt252, core::felt252, core::byte_array::ByteArray)>",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::reclaim::reclaim::MetadataSaved",
          kind: "struct",
          members: [
            {
              name: "hash_commit",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "unlock_timestamp",
              type: "core::felt252",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::reclaim::reclaim::FileReclaimed",
          kind: "struct",
          members: [
            {
              name: "hash_commit",
              type: "core::felt252",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::reclaim::reclaim::Event",
          kind: "enum",
          variants: [
            {
              name: "MetadataSaved",
              type: "contracts::reclaim::reclaim::MetadataSaved",
              kind: "nested",
            },
            {
              name: "FileReclaimed",
              type: "contracts::reclaim::reclaim::FileReclaimed",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x2c739acfd18c678d096d0a8b224fe589303bbba786ea3d579c9457af1fe15f6",
    },
  },
  sepolia: {
    reclaim: {
      address:
        "0x556c797acae1da7833124db8846105427fdc2d9dc6b16a45fbbfc1cc93b36c1",
      abi: [
        {
          type: "impl",
          name: "ReclaimImpl",
          interface_name: "contracts::reclaim::IReclaim",
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::reclaim::IReclaim",
          items: [
            {
              type: "function",
              name: "save_metadata",
              inputs: [
                {
                  name: "hash_commit",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "cipher_secret",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "cid",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "unlock_timestamp",
                  type: "core::felt252",
                },
                {
                  name: "access_type",
                  type: "core::felt252",
                },
                {
                  name: "name",
                  type: "core::byte_array::ByteArray",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "reclaim",
              inputs: [
                {
                  name: "hash_commit",
                  type: "core::byte_array::ByteArray",
                },
              ],
              outputs: [
                {
                  type: "(core::byte_array::ByteArray, core::byte_array::ByteArray, core::felt252, core::felt252, core::felt252, core::byte_array::ByteArray)",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_records_by_owner",
              inputs: [
                {
                  name: "owner",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::array::Array::<(core::byte_array::ByteArray, core::felt252, core::felt252, core::felt252, core::byte_array::ByteArray)>",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::reclaim::reclaim::MetadataSaved",
          kind: "struct",
          members: [
            {
              name: "hash_commit",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "unlock_timestamp",
              type: "core::felt252",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::reclaim::reclaim::FileReclaimed",
          kind: "struct",
          members: [
            {
              name: "hash_commit",
              type: "core::felt252",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::reclaim::reclaim::Event",
          kind: "enum",
          variants: [
            {
              name: "MetadataSaved",
              type: "contracts::reclaim::reclaim::MetadataSaved",
              kind: "nested",
            },
            {
              name: "FileReclaimed",
              type: "contracts::reclaim::reclaim::FileReclaimed",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x1c0b2e8a73fbacb38cfe0a62903796d7ef784c48ea3fc192a8786be225b3fa3",
    },
  },
} as const;

export default deployedContracts;
